export const CHANGE_ACTIVE_SONG_INDEX = 'CHANGE_ACTIVE_SONG_INDEX';
export const FETCH_SONGS = 'FETCH_SONGS';
export const RECEIVE_SONGS = 'RECEIVE_SONGS';
export const REQUEST_SONGS = 'REQUEST_SONGS';
