export const ADD_SONGS_TO_PLAYLIST = 'ADD_SONGS_TO_PLAYLIST';
export const CHANGE_ACTIVE_SONG_INDEX = 'CHANGE_ACTIVE_SONG_INDEX';
export const CHANGE_CATEGORY = 'CHANGE_CATEGORY';
export const FETCH_SONGS = 'FETCH_SONGS';
export const PLAY_SONG = 'PLAY_SONG';
export const RECEIVE_SONGS = 'RECEIVE_SONGS';
export const REQUEST_SONGS = 'REQUEST_SONGS';
export const SET_PLAYLIST_SONGS = 'SET_PLAYLIST_SONGS';
